ALTER TABLE users ADD COLUMN IF NOT EXISTS pincode VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE users ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

CREATE INDEX IF NOT EXISTS idx_users_pincode ON users(pincode);
