ALTER TABLE doctors ADD COLUMN IF NOT EXISTS clinic_address TEXT;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
