CREATE SEQUENCE IF NOT EXISTS marg_order_id_seq START 100000;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS marg_order_id INTEGER UNIQUE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS marg_order_no TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS marg_pushed_at TIMESTAMPTZ;
